models/Calendar.php
<?php

namespace app\models;

use yii;

class Calendar extends \yii\db\ActiveRecord
{
    public function rules()
    {
        return [
            [['date', 'meal_id'], 'required'],
            [['meal_id'], 'integer', 'min' => 0],
            [['meal_id'], 'integer', 'max' => 4294967295],
            [['date'], 'date'],
        ];
    }

    /**
     * @return string the name of the table associated with this ActiveRecord class.
     */
    public static function tableName()
    {
        return 'calendars';
    }

    public function getMeal()
    {
        return $this->hasOne(Meal::className(), ['id' => 'meal_id']);
    }

    public function beforeSave($insert)
    {
        if (!parent::beforeSave($insert)) {
            return false;
        }


        $this->last_edited_at = date('Y-m-d: H:i:s');
        return true;
    }
}

models/Ingredient.php
<?php

namespace app\models;

use yii;

class Ingredient extends \yii\db\ActiveRecord
{
    private static $units = [
        null => '',
        0 => 'pcs',
        1 => 'kg',
        2 => 'g',
        3 => 'ml',
        4 => 'L'
    ];

    public function rules()
    {
        return [
            [['meal_id', 'name', 'amount', 'unit'], 'required'],
            [['meal_id', 'amount', 'unit'], 'integer', 'min' => 0,  'max' => 4294967295],
            [['name'], 'string', 'max' => 255]
        ];
    }

    /**
     * @return string the name of the table associated with this ActiveRecord class.
     */
    public static function tableName()
    {
        return 'ingredients';
    }

    public function getMeal()
    {
        return $this->hasOne(Meal::className(), ['id' => 'meal_id']);
    }

    /**
     * @return string unit of the ingredient
     */
    public function getUnit()
    {
        return self::$units[$this->unit];
    }

    public static function getUnits()
    {
        return self::$units;
    }
}

models/Meal.php
<?php

namespace app\models;

use Yii;

class Meal extends \yii\db\ActiveRecord
{
    private static $categories = [
        null => [
            'category' => '(not set)',
            'default_img' => '/img/default/unknown.svg'
        ],
        0 => [
            'category' => 'breakfast',
            'default_img' => '/img/default/breakfast.svg'
        ],
        1 => [
            'category' => 'lunch',
            'default_img' => '/img/default/lunch.svg'
        ],
        2 => [
            'category' => 'snack',
            'default_img' => '/img/default/snack.svg'
        ],
        3 => [
            'category' => 'dinner',
            'default_img' => '/img/default/dinner.svg'
        ],
    ];

    public function rules()
    {
        return [
            [['name'], 'required'],
            [['category', 'rating'], 'integer', 'min' => 0, 'max' => 4294967295],
            [['description', 'image'], 'string', 'max' => 255],
            [['comments'], 'string', 'max' => 65535]
        ];
    }

    /**
     * @return string the name of the table associated with this ActiveRecord class.
     */
    public static function tableName()
    {
        return 'meals';
    }

    public function getIngredients(){
        return $this->hasMany(Ingredient::className(), ['meal_id' => 'id']);
    }

    public function getCalenders(){
        return $this->hasMany(Calendar::className(), ['meal_id' => 'id']);
    }

    public function beforeValidate()
    {
        if($this->image === null || empty($this->image)){
            $this->image = self::$categories[$this->category]['default_img'];
        }
        return true;
    }

    public function getCategory()
    {
        return self::$categories[$this->category]['category'];
    }

    public static function getCatergories(){
        $categories = [null=>self::$categories[null]['category']];
        foreach(array_slice(self::$categories,1) as $cat){
            array_push($categories, $cat['category']);
        }

        return $categories;
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Calendar;
use app\models\Ingredient;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\Meal;
use DateInterval;
use DatePeriod;
use DateTime;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ]
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $weekDinner =  Calendar::find()
            ->joinWith('meal', true)
            ->joinWith('meal.ingredients', true)
            ->where(['between', 'date', date('Y-m-d'),  date("Y-m-d", strtotime("+1 week"))])
            ->andWhere(['meals.category' => 3])
            ->orderBy('date')
            ->all();

        // return var_dump($weekDinner);

        return $this->render('index', [
            'todayDinner' => $weekDinner[0], //TODO:  only true if today has an entry
            'weekDinners' => array_slice($weekDinner, 1)
        ]);
    }

    public function actionInfo()
    {
        $meals = Meal::find()->all();
        return $this->render('info', [
            'meals' => $meals
        ]);
    }

    public function actionAdd_meal()
    {
        $mealModel = new Meal();
        $ingredientModel = new Ingredient();
        return $this->render('add_meal', [
            'mealModel' => $mealModel
        ]);
    }

    public function actionNew_meal()
    {

        $post = Yii::$app->request->post();

        if (!empty($post)) {
            // add meal to db, get meal id for later use
            $meal = new Meal();

            if ($meal->load($post) && $meal->validate() && $meal->save()) {

                // add ingredients to meal, meal id required
                $ingredients = $this->get_ingredients($post);
                $success = true;
                foreach ($ingredients as $ingredient) {
                    $i = new Ingredient();
                    $i->name = $ingredient['name'];
                    $i->amount = $ingredient['amount'];
                    $i->unit = $ingredient['unit'];
                    $i->meal_id = $meal->id;
                    $success = $success & $i->save();
                }
                if ($success) {
                    Yii::$app->session->setFlash('success', 'Meal and ingredients added!');
                } else {
                    Yii::$app->session->setFlash('warning', 'Not all ingredients could be added to the meal');
                }
            } else {
                Yii::$app->session->setFlash('danger', 'Meal could not be created');
            }
            return $this->redirect('add_meal');
        }
        return $this->redirect('add_meal');
    }

    /**
     * @return array array containing the ingredients, empty if not found
     */
    private function get_ingredients($post)
    {
        if (key_exists('ingredients', $post)) {
            parse_str($post['ingredients'], $post_ing);
            if (key_exists('Ingredient', $post_ing)) {
                return $post_ing['Ingredient'];
            }
        }
        return [];
    }

    public function actionSchema()
    {
        if (isset($_GET) && array_key_exists('id', $_GET)) {
            $id = $_GET['id'];
            $meal = Meal::findOne($id);
            $current_cal = Calendar::find()
                ->where(['meal_id' => $meal->id])
                ->andWhere(['>', 'date', date('Y-m-d')])
                ->all();;
        }

        $period = new DatePeriod(
            new DateTime(date('Y-m-d')),
            new DateInterval('P1D'),
            new DateTime(date("Y-m-d", strtotime("+1 month")))
        );
        return $this->render('schema', [
            'current_cal' => $current_cal,
            'meal' => $meal,
            'period' => $period
        ]);
    }

    public function actionNew_schema()
    {
        return $this->redirect('schema');
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">

<head>
	<meta charset="<?= Yii::$app->charset ?>">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<?= Html::csrfMetaTags() ?>
	<title><?= Html::encode($this->title) ?></title>
	<?php $this->head() ?>
</head>

<body>
	<?php $this->beginBody() ?>
	<div class="wrap">
		<?php
		NavBar::begin([
			'brandLabel' => 'Bare',
			'brandUrl' => Yii::$app->homeUrl,
			'options' => [
				'class' => 'navbar-inverse navbar-fixed-top',
				//'style' => 'background-color:#B41F21',
			],
		]);
		echo Nav::widget([
			'options' => ['class' => 'navbar-nav navbar-right'],
			'items' => [
				['label' => 'Home', 	'url' => Yii::$app->homeUrl],
				['label' => 'info', 	'url' => ['/site/info']],
				['label' => 'Schema','url' => ['/site/schema']],
			],
		]);
		NavBar::end();
		?>
		<div class="container">
			<?= Breadcrumbs::widget([
				'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
			]) ?>

			<?php
			foreach (Yii::$app->session->getAllFlashes() as $key => $message) :
				if ($key == 'error') {
					$key = 'danger';
				} ?>
				<?= '<div class="alert alert-' . $key . '">' . $message . "</div>\n" ?>
			<?php endforeach; ?>

			<?= $content ?>
		</div>
	</div>




	<footer class="footer">
		<div class="container">
			<p class="pull-left">&copy; Bram den Ouden <?= date('Y') ?></p>

			<p class="pull-right"><?= Yii::powered() ?></p>
		</div>
	</footer>

	<?php $this->endBody() ?>
</body>
<script>
	$(document).ready(function() {
		$('[data-toggle="tooltip"]').tooltip();
	});
	$('a[href*="http"]').attr('target', '_blank'); // change external links to open in new tab
</script>

</html>
<?php $this->endPage() ?>

views/site/add_ingredient.php
<?php

use app\models\Ingredient;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

$form = ActiveForm::begin([
    'id' => 'add-ingredient-form',
    'layout' => 'default',
]); ?>
<style>
@media screen and (max-width:450px){
    .unit{
        width: 25%;
    }
    .remove{
        margin-left: 0;
    }
}

</style>


<h2 style="text-align:center">
    Ingredients
    <button class="btn btn-success" type="button" style="margin: 10px" onclick="addFormField()">
        <span class="glyphicon glyphicon-plus"></span>
    </button>
</h2>
<div class="form-inline">
    <!-- <div class="col-sm-offset-2 col-sm-3 col-xs-offset-1 col-xs-3">
        <?= Html::activeLabel($ingredientModel, 'name') ?>
    </div>
    <div class="col-sm-3 col-xs-3">
        <?= Html::activeLabel($ingredientModel, 'amount') ?>
    </div>
    <div class="col-sm-2 col-xs-2">
        <?= Html::activeLabel($ingredientModel, 'unit') ?>
    </div> -->

    <div id="ingredient-container"></div>
</div>
<div style="text-align:center">
    <button class="btn btn-primary add-item-button" type="button" style="margin:10px;" onclick="addMeal()">Add meal</button>
</div>
<?php
ActiveForm::end();
?>

<script>
    var i = 0;

    function addFormField() {
        var container = document.getElementById('ingredient-container');
        var row = document.createElement('div');
        row.setAttribute('class', 'row');
        row.innerHTML = getHtml(i);
        container.appendChild(row);
        addValidator(i);
        $('[data-toggle="tooltip"]').tooltip();

        i += 1;
    }

    function addValidator(rowNo) {
        // name validator
        $('#add-ingredient-form').yiiActiveForm('add', {
            id: 'ingredient-name-' + rowNo,
            name: 'name',
            container: '.field-ingredient-name-' + rowNo,
            input: '#ingredient-name-' + rowNo,
            error: '.help-block',
            validate: function(attribute, value, messages, deferred, $form) {
                yii.validation.required(value, messages, {
                    message: "Name cannot be blank."
                });
                yii.validation.string(value, messages, {
                    message: "Name must be a string.",
                    max: 255,
                    skipOnEmpty: 1,
                    tooLong: "Name should contain at most 255 characters.",
                });
            }
        });

        // amount validator
        $('#add-ingredient-form').yiiActiveForm('add', {
            id: 'ingredient-amount-' + rowNo,
            name: 'amount',
            container: '.field-ingredient-amount-' + rowNo,
            input: '#ingredient-amount-' + rowNo,
            error: '.help-block',
            validate: function(attribute, value, messages, deferred, $form) {
                var name = attribute.name.substr(0, 1).toUpperCase() + attribute.name.substr(1); // capitalize first letter of name
                yii.validation.required(value, messages, {
                    message: name + " cannot be blank."
                });
                yii.validation.number(value, messages, {
                    pattern: /^\s*[+-]?\d+\s*$/,
                    min: 0,
                    tooSmall: name + " must be no less than 0.",
                    max: 4294967295,
                    tooBig: name + " must be no greater than 4294967295.",
                    message: name + " must be an integer.",
                    skipOnEmpty: 1
                });
            }
        });

        // unit validator
        $('#add-ingredient-form').yiiActiveForm('add', {
            id: 'ingredient-unit-' + rowNo,
            name: 'unit',
            container: '.field-ingredient-unit-' + rowNo,
            input: '#ingredient-unit-' + rowNo,
            error: '.help-block',
            validate: function(attribute, value, messages, deferred, $form) {
                var name = attribute.name.substr(0, 1).toUpperCase() + attribute.name.substr(1); // capitalize first letter of name
                yii.validation.required(value, messages, {
                    message: name + " cannot be blank."
                });
                yii.validation.number(value, messages, {
                    pattern: /^\s*[+-]?\d+\s*$/,
                    min: 0,
                    tooSmall: name + " must be no less than 0.",
                    max: 4294967295,
                    tooBig: name + " must be no greater than 4294967295.",
                    message: name + " must be an integer.",
                    skipOnEmpty: 1
                });
            }
        });
    }

    function getHtml(rowNo) {
        return `
        <div class="row" id ="row-${rowNo}">
            <div class="col-sm-offset-2 col-sm-3 col-xs-offset-1 col-xs-3">
                <div class="form-group field-ingredient-name-${rowNo} required">
                    <input type="text" id="ingredient-name-${rowNo}" class="form-control" name="Ingredient[${rowNo}][name]" aria-required="true" placeholder="Name">
                    <p class="help-block help-block-error"></p>
                </div>        
            </div>
            <div class="col-sm-3 col-xs-3">
                <div class="form-group field-ingredient-amount-${rowNo} required">
                    <input type="text" id="ingredient-amount-${rowNo}" class="form-control" name="Ingredient[${rowNo}][amount]" aria-required="true" placeholder="Amount">
                    <p class="help-block help-block-error"></p>
                </div>
            </div>
            <div class="col-sm-2 col-xs-2 unit">
                <div class="form-group field-ingredient-unit-${rowNo} required">
                    <select id="ingredient-unit-${rowNo}" class="form-control" name="Ingredient[${rowNo}][unit]" aria-required="true">
                        <option selected disabled value="">Unit</option>
                        <option value="0">pcs</option>
                        <option value="1">kg</option>
                        <option value="2">g</option>
                        <option value="3">ml</option>
                        <option value="4">L</option>
                    </select>
                    <p class="help-block help-block-error"></p>
                </div>        
            </div>
            <div class="col-sm-1 col-xs-offset-1 col-xs-1 remove">
                <div class="form-group">
                    <span style="margin-top:7px" class="glyphicon glyphicon-remove"
                        onclick="$('#row-${rowNo}').remove()"
                        data-toggle="tooltip"
                        title='Remove ingredient'
                        ></span>
                </div
            </div>
        </div>
        `;
    }

    function addMeal() {
        if (checkInput()) {
            var $mealForm = $('#add-meal-form');
            var $ingForm = $('#add-ingredient-form');
            var ingData = $ingForm.serialize();
            document.getElementById('meal-ingredients').value = ingData;
            $mealForm.submit();
        }
    }

    function checkInput() {
        var $form = $('#add-ingredient-form'),
            data = $form.data('yiiActiveForm');
        $.each(data.attributes, function() {
            this.status = 3;
        });
        $form.yiiActiveForm('validate');

        if ($form.find('.has-error').length) {
            // console.log('errors found');
            return false;
        } else {
            // console.log('no errors found');
            return true;
        }
    }
</script>

views/site/add_meal.php
<?php

/* @var $this yii\web\View */

use app\models\Ingredient;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use app\models\Meal;

$this->title = 'add-meal';

?>
<div class="site-add_meal">

    <h1>Add Meal</h1>

    <?php
    $form = ActiveForm::begin([
        'id' => 'add-meal-form',
        'action' => 'new_meal',
        'layout' => 'horizontal',
    ]);
    ?>
    <div class="row col-sm-12">
        <h2 style="text-align:center">Meal properties</h2>
        <?= $form->field($mealModel, 'name')->textInput()->hint('The name of the dish') ?>
        <?= $form->field($mealModel, 'description')->textInput()->hint('Describe your dish') ?>
        <?= $form->field($mealModel, 'category')->dropDownList(Meal::getCatergories())->hint('What category suits your dish best?') ?>
        <?= $form->field($mealModel, 'image')->textInput()->hint('URL to a picture of your dish') ?>
        <input type="hidden" id="meal-ingredients" name="ingredients" value="">
    </div>

    <?php ActiveForm::end() ?>

    <?= $this->render('add_ingredient', ['ingredientModel' => new Ingredient()]); ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'Bare';
?>
<style>
  @media screen and (max-width:600px) {
    .meal-of-the-day, .week-meal{
      width: 100%;
    }

  }
</style>
<div class="site-index">

  <h1>Dinner</h1>
  <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. Donec non enim in turpis pulvinar facilisis. Ut felis. Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat. Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus, metus</p>
  <a href="add_meal">Add meal</a>
  <p>
    foreach meal -> get day, get img, get caption, get description, get ingredients<br>
    foreach ingredient (linked by meal id)-> get name, get amount</p>

  <div class="col-md-4 col-xs-6 meal-of-the-day">
    <div class="thumbnail">
      <img src="<?= $todayDinner->meal->image ?>" alt="...">
      <div class="caption">
        <h3><?= $todayDinner->meal->name ?></h3>
        <p><?= $todayDinner->meal->description ?></p>
        <?php
        $ingredients = $todayDinner->meal->ingredients; ?>
        <?= $ingredients ? '' : 'No ingredients set' ?>
        <table class="table table-bordered">
          <tr>
            <th colspan='2'>Ingredients</th>
          </tr>
          <?php foreach ($ingredients as $ingredient) : ?>
            <tr>
              <td class="col-xs-6"><?= $ingredient->name ?></td>
              <td class="col-xs-6"><?= $ingredient->amount . ' ' . $ingredient->getUnit() ?></td>
            </tr>
          <?php endforeach; ?>
        </table>
        <!-- <p style="text-align: center"><a href="#" class="btn btn-primary" role="button">Add comment</a></p>
        <p style="text-align: center"><a href="#" class="btn btn-link" role="button">Rate meal</a></p> -->
      </div>
      <div><?= date("l j F Y", strtotime($todayDinner->date)) ?></div>
    </div>
  </div>

  <?php foreach ($weekDinners as $dinner) : ?>
    <div class="col-md-4 col-xs-6 week-meal">
      <div class="panel panel-default">
        <div class="panel-heading">
          <b>
            <?= date("l", strtotime($dinner->date)) ?>
          </b>
          <span class="pull-right">
            <?= ' ' . $dinner->date ?>
          </span>
        </div>
        <div class="panel-body">
          <p>Title: <?= $dinner->meal->name ?></p>
          <p>Description: <?= $dinner->meal->description ?></p>
        </div>
      </div>
    </div>
  <?php endforeach; ?>
</div>

views/site/info.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'Bare';
?>

<style>
  .thumbnail:hover{
    box-shadow:0 0 7px #6b6b6b;
  }

</style>

<div class="site-info">

  <h1>Meals</h1>
  <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. Donec non enim in turpis pulvinar facilisis. Ut felis. Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat. Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus, metus</p>

  <?php foreach ($meals as $meal) : ?>
    <div class="col-sm-3 col-xs-6">
      <div class="thumbnail" data-toggle="tooltip" title="Click to (re)schedule meal" onclick="location.href='/schema?id=<?=$meal->id?>'">
        <img src="<?= $meal->image ?>" alt="<?= $meal->getCategory() ?>">
        <div class="caption">
          <h3><?= $meal->name ?></h3>
          <p><?= $meal->description ?></p>
          <p><?= $meal->getCategory() ?></p>
        </div>
      </div>
    </div>

  <?php endforeach; ?>

</div>

views/site/schema.php
<?php

/* @var $this yii\web\View */

use yii\bootstrap\ActiveForm;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;

$this->title = 'schema';
?>
<style>
    .cal-container {
        display: flex;
        flex-wrap: wrap;
        /* justify-content: center; */
        align-items: center;
        width: 100%;

        /*align-content: flex-start; */
    }

    .cal-date-box {
        display: flex;
        text-align: center;
        flex-direction: column;
        width: 100px;
        height: 100px;
        border: 0.5px solid #ddd;
    }

    .cal-date {
        font-weight: bold;
    }

    .cal-date-box>b {
        margin: 0 auto auto auto;
    }

    .selected {
        background-color: #f5f5f5;
    }

    .cal-checkbox {
        font-size: 25px;
        margin: auto;
    }
</style>
<div class="site-schema">

    <h1>Schema</h1>
    <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. Donec non enim in turpis pulvinar facilisis. Ut felis. Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat. Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus, metus</p>
    <div class="row">
        <div class="col-xs-offset-3 col-xs-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <b><?= $meal->name ?></b>

                </div>
                <div class="panel-body">
                    <p>Title: <?= $meal->name ?></p>
                    <p>Description: <?= $meal->description ?></p>
                </div>
            </div>
        </div>
    </div>

    <?php
    // var_dump($meal, $current_cal, $period);

    $dates = ArrayHelper::getColumn($current_cal, 'date');
    ?>

    <div class="row">
        <div class="cal-container col-md-12">
            <?php foreach ($period as $key => $value) : ?>
                <div onclick="toggle(this)" class="cal-date-box <?= in_array($value->format('Y-m-d'), $dates) ? 'selected' : '' ?>">
                    <div class="cal-date" value ="<?= $value->format('d-m-Y')?>" >
                        <?= $value->format('d-m-Y')?>
                    </div>
                    <div class="cal-checkbox">
                        <?= in_array($value->format('Y-m-d'), $dates) ? '<span class="glyphicon glyphicon-ok"></span>' : '' ?>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>

    <form method="post" id="cal-update-form">
        <input type="hidden" name="<?= Yii::$app->request->csrfParam; ?>" value="<?= Yii::$app->request->csrfToken; ?>" />
        <input id="calendar-meal_id" type="hidden" name="meal_id" value="">
        <input id="calendar-dates" type="hidden" name="dates" value="">
    </form>


    <button onclick="getSelected()">test</button>
</div>

<script>
    var mealId = <?= $meal->id ?>;

    function toggle(e) {
        if (e.classList.contains("selected")) {
            deselect(e);
        } else {
            select(e);
        }
    }

    function deselect(e) {
        e.classList.remove('selected')
        var cb = e.getElementsByClassName('cal-checkbox')[0];
        cb.innerHTML = '';
    }

    function select(e) {
        e.classList.add('selected');
        var cb = e.getElementsByClassName('cal-checkbox')[0];
        cb.innerHTML = '<span class="glyphicon glyphicon-ok"></span>';
    }

    function getSelected() {
        var elements = document.getElementsByClassName('selected');
        var dates = []; // array containing the selected dates
        for (let i = 0; i < elements.length; i++) {
            dates.push(elements[i].getElementsByClassName('cal-date')[0].getAttribute('value'));            
        }
        document.getElementById('calendar-meal_id').value = mealId;
        document.getElementById('calendar-dates').value = JSON.stringify(dates);
        $('#cal-update-form').submit();
    }
</script>